baseURL = "https://golden-goose-lab.github.io"
languageCode = "ko-kr"
title = "Golden Goose Lab"
theme = "anubis"
paginate = 5

disqusShortname = ""
googleAnalytics = ""

[author]
  name = "Golden Goose Lab"

[params]
   author = "Golden Goose Lab"
   description = "황금알을 낳는 기술을 연구합니다."

[menu]

  [[menu.main]]
    identifier = "about"
    name = "소개"
    url = "/about/"
    weight = 1

  [[menu.main]]
    name = "글"
    identifier = "archive"
    url = "/posts/"
    weight = 3

[taxonomies]
category = "categories"
tag = "tags"
series = "series"